services:
  sut:
    build: .
    environment:
      NODE_ENV: 'test'
    depends_on:
      - server
  server:
    image: neoskop/ethereal-secrets-server
    depends_on:
      - redis
  redis:
    image: redis
