version: "3"
services:
  sut:
    build: .
    environment:
      NODE_ENV: "test"
    depends_on:
      - server
  server:
    image: neoskop/ethereal-secrets-server
    logging:
      driver: "none"
    depends_on:
      - redis
  redis:
    image: redis
    logging:
      driver: "none"
