version: "3"
services:
  app:
    build: .
    command: npm start
    environment:
      NODE_ENV: "test"
    depends_on:
      - server
    volumes:
      - ./src:/home/node/src:ro
  server:
    image: neoskop/ethereal-secrets-server
    logging:
      driver: "none"
    depends_on:
      - redis
  redis:
    image: redis
    logging:
      driver: "none"
