services:
  app:
    build: client
    command: npm start
    environment:
      NODE_ENV: "test"
    depends_on:
      - server
    volumes:
      - ./client/src:/home/node/src:ro
  server:
    build: server
    environment:
      SECURE_COOKIE: "false"
    depends_on:
      - redis
    volumes:
      - ./middleware:/home/node/node_modules/@neoskop/ethereal-secrets-middleware:ro
  redis:
    image: redis
