services:
  app:
    build: .
    environment:
      NODE_ENV: 'development'
    depends_on:
      - redis
    volumes:
      - ./src:/home/node/src:ro
    ports:
      - 8080:8080
  redis:
    image: redis
