services:
  app:
    build: .
    command: npm start
    environment:
      NODE_ENV: 'development'
    depends_on:
      - redis
    volumes:
      - ./src:/home/node/src:ro
    ports:
      - 9229:9229
  redis:
    image: redis@sha256:2c2dff791878316e3b083188be0d578423b24813cdda5de0e80ea4f7b3e6bfd6
