version: "2.4"
services:
  app:
    build: .
    command: npm start
    environment:
      NODE_ENV: "development"
    depends_on:
      - redis
    volumes:
      - ./src:/home/node/src:ro
    ports:
      - 9229:9229
  redis:
    image: redis