services:
  app:
    build: .
    command: npm start
    environment:
      NODE_ENV: 'development'
    depends_on:
      - redis
    volumes:
      - ./src:/home/node/src:ro
    ports:
      - 9229:9229
  redis:
    image: redis@sha256:718f745deb7dfefeac6eed7041fc7ec9476b50e61b247932682457c41adafa0e
