services:
  app:
    build: .
    command: npm start
    environment:
      NODE_ENV: 'development'
    depends_on:
      - redis
    volumes:
      - ./src:/home/node/src:ro
    ports:
      - 9229:9229
  redis:
    image: redis@sha256:234c902a2db49461a129e2d4aeff85b28cf20187ed274a67f6e50995fa713c7b
